Release 2025-11-23
Features:
- Added Ring Racers HEP (HEP4), SRB2 v2.2 Beta 6 (Recreation by XDF22), SRB2 1095 (fork of SRB2-OLD and Final Demo by CG64), Ultimate GKSZ Builder (fork of UZB by GLideKS, issue #37),
- Added menu to manage custom builds when installing, uninstalling, removing source code and listing.

Fixes:
- Improved downloading and extraction of proper version of assets for SRB2, SRB2 Kart, BlanKart and Ring Racers,
- Fixed issue of not dynamically added correct hash values to code for assembled assets of Blankart (issue #36 and #38),
- Fixed issue of not finding external/ogg due to download script not initiliazed for BlanKart on Windows,
- Added openal-soft library to BlanKart,
- Fixed issue of patches of SRB2 Community Build for Windows causing compiling errors on Linux,
- Fixed SRB2 JTE not finding Makefile,
- Removed carriage returns from code for NewMillennium for patches to be applied on Windows,
- Replaced internal types to portable ones for SRB2 Kart Saturn for compatibility with Alpine Linux,
- Replaced header threads.h to pthread.h for SRB2 Kart Saturn due to be missing in Docker/Podman container,
- Added libbacktrace to SRB2 Kart Saturn for Windows,
- Added missing c++ compiler to SRB2 Kart Saturn,
- Fixed error SDK_HINT_AUTO_UPDATE_SENSORS by upgrading SDL2 for SRB2 Kart Saturn for Linux,
- Fixed error of missing i_system.cpp for SRB2 Kart Saturn,
- Added patch to SRB2 Kart Saturn to fix compilation on macOS,
- Added missing header stdbool.h for errors with unknown type bool for SRB2 Kart Saturn on Windows,
- Added the EffectThingAnchorSlope.cs reference to BuilderMono.csproj file to fix "error CS0246: The type or namespace name 'EffectThingAnchorSlope' could not be found" for High Voltage Ring,
- Fixed missing Makefile for SRB2 Classic due to upstream using CMake now for compiling,
- Fixed issue of not copying of binaries for old 32-bit builds,
- Fixed issue of not displaying icon for SRB2 Classic and SRB2 Community Build on Linux,
- Fixed issue of not installing on macOS due to missing libbrotlicommon.dylib,
- Corrected UZB, ULB, HVR folder names to source code,
- Fixed issue of copying duplicated libraries for Windows,
- Replaced link to wadcli, kartmaker and followermaker's icon,
- Some corrections to AppImage names.

Other:
- Added missing dependencies to README.md for macOS,
- Replace link to repository of SRB2 Reveries,
- Removed SRB2 Kart Moe Mansion, Ring Racers HEP2 and Ring Racers HEP3,
- Updated note to compilation errors,
- Updated compatibility table,
- Updated README.md,
- Removed unused code,
- Refactored code.